# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-30 03:51
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoastlinePolygons',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('plateid1', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('type', models.CharField(blank=True, max_length=80, null=True)),
                ('fromage', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('toage', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4269)),
            ],
            options={
                'db_table': 'coastline_polygons',
                'managed': False,
            },
        ),
    ]
